version: "3.5"
services:
  chat-px-api:
    build:
      context: .
      dockerfile: Dockerfile
    #volumes:
    #  - .:/usr/src/api
    #  - /usr/src/api/node_modules
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=${NODE_ENV}
